### ISSUE TITLE
Keuzehulp verwerken

### ISSUE THREAD

**Issue by lvdbrink** [lvdbrink/geox#14]
Het diagram "keuzehulp" is al in het document opgenomen en klikbaar gemaakt. 

In de tekst nog een toelichting op hoe het diagram gebruikt kan worden opnemen waarin oa staat: 
- dat je kan klikken op de formaten
- dat de keuzehulp vooral bedoeld is als ingang op het document maar dat je om een goede beslissing te maken de verdere toelichting moet lezen

**Comment by gabswiersma** [comment]
To do, later aanpassen in diagram: 

- GeoJSON en ondersteuning van 3D
- Balk ''complexiteit'' verwijderen

**Comment by lvdbrink** [comment]
Ik heb voor die dingen een apart issue #15 opgenomen. Dus als je de toelichting hebt geschreven kan dit issue gesloten worden.
