### ISSUE TITLE
Ter overweging: HTML ook opnemen?

### ISSUE THREAD

**Issue by thijsbrentjens** [lvdbrink/geox#2]
Voor publicatie op het web kan HTML ook een geschikte encoding zijn van geodata. Deze staat niet in dit document. Is dit bewust buiten scope gehouden of is het juist goed om hier ook iets over op te nemen?

**Comment by thijsbrentjens** [comment]
@lvdbrink  Ik heb een begin gemaakt, om duidelijk te maken waarom. https://github.com/thijsbrentjens/geox/tree/html
Is dat iets? Dan maak ik een PR en kunnen we (samen) verder werken via master. Als je denkt dat het geen plaats heeft in dit document, dan komt het misschien wel ergens anders van pas.

**Comment by lvdbrink** [comment]
Ja, ik vind het een goede toevoeging @thijsbrentjens ! Graag een PR 👍
