### ISSUE TITLE
3D in GeoJSON

### ISSUE THREAD

**Issue by lvdbrink** [lvdbrink/geox#5]
Lennart van Bergen: 

> GeoJson ondersteund gewoon “height”, oftewel 2.5D of 3D (ik had gezocht op srsDimension of Z). 
> 
> Er is een standaard conventie om in de array items met blokhaken op te nemen, dus: [1,2,3],[4,5,6,] etc bij 3D. 
> 
Dit nagaan en de positionering van GeoJSON aanpassen.

**Comment by lvdbrink** [comment]
conventie over blokhaken opnemen in Afspraken bij GeoJSON.

**Comment by gabswiersma** [comment]
Array items in blokhaken beschrijven we in een voorbeeld, zie #16
