### ISSUE TITLE
Naamgevingsconventies in uitwisselformaten

### ISSUE THREAD

**Issue by JvGldr** [lvdbrink/geox#7]
Er is behoefte aan standaardisatie van de namen van objecten, features en properties in de data die uitgewisseld wordt.
het gaat om:
GeoPackage
JSON
GeoJSON
XML
GML

E.e.a. is uitgezocht en kan worden onderbouwd. 
Uitkomst is:
GeoPackage zegt snake_case
JSON (en dus ook GeoJSON) zegt lowerCamelCase
XML zegt er niet zoveel over
GML zegt UpperCamelCase voor Objects en Features en lowerCamelCase voor properties.

Voorstel: een paragraaf hierover over opnemen in het document. 
[Naamgeving Uitwisselformaten v1.0.0.docx](https://github.com/Geonovum/geox/files/5819407/Naamgeving.Uitwisselformaten.v1.0.0.docx)

**Comment by lvdbrink** [comment]
Opnemen onder kopje "Afspraken" in hfd 4-8.
